### DISCUSSION TITLE
Shortcut for formatting text

### DISCUSSION THREAD

**Discussion by GusGF** [freeplane/freeplane#599] [Help]
I want to see if I can format specific spans of text in my nodes e.g. where I insert pastes of code. I would use a specific font and text size and it would save me time rather than having to do it manually every time. Any ideas anyone?

BTW I'm aware one can copy from VSCode and the necessary formatting is included so it looks like a clip of code from VScode in the FP node, but I don't always have this option.

**Comment by euu2021** [comment]
> I want to see if I can format specific spans of text in my nodes [...]

Are you looking for something like Styles in a word processor?

**Reply by GusGF** [reply]
Perhaps, would that set font size, colour and font?

**Comment by EdoFro** [comment]
Here is a way to use markdown and css to have "code blocks" style in notes (you can do the same for node's texts or details)

When applied it looks like this: (I just copied a [comment from another discussion](https://github.com/freeplane/freeplane/discussions/496#discussioncomment-3502705) as markdown in a node's note)
![image](https://user-images.githubusercontent.com/35700575/187502124-b273d310-a3bf-4855-839b-3a5428c6a53c.png)

You just have to add the css specification for blocks in the style or nodes you want.

I used this css code for the example:

```css
pre {
    background-color: #006666;
    border-left: 5px solid #00FFFF;
    display: block;
    padding: 8px;
    margin: 5px;
}
code {
    font-family: Consolas,"courier new";
    font-size: 11px;
    color: #99ffff;
}
blockquote {
    border-left: 5px solid #00FF00;
    background-color: #eeeeee;
    padding: 8px;
}

```

the example mindmap:
[css -codeblock.zip](https://github.com/freeplane/freeplane/files/9455266/css.-codeblock.zip)

hope it helps,
edo
